### ISSUE TITLE
Uncaught TypeError; Cannot read property 'split' of null

### ISSUE THREAD

**Issue by r6d2** [Revadike/EnhancedBarter#1]
I get this message every time and no offers are generated. Any ideas?
https://gyazo.com/9e233f49a04121ca5aee82209a545f35
https://gyazo.com/b1f673d8701a9e20781a20f18a66307a
Thanks in advance!

**Comment by Revadike** [comment]
What does it show if u click on the link to the right?
![image](https://user-images.githubusercontent.com/4411977/35021289-877d2566-fb30-11e7-8742-5dc872f6ab2a.png)
