### ISSUE TITLE
Feature Idea: Recieve automated offer preference configuration

### ISSUE THREAD

**Issue by goplayer7** [Revadike/EnhancedBarter#17]
The intent of this is to allow users to set more strict settings on what they want to receive from automated offers than what they would generally accept from users in general. This would provide a middle ground solution between the extremes of having users be forced to accept any offer that they would accept from regular offers or no offers at all

Minimum Feature Implementation Idea: A button for users to say "I only want to receive offers that involve wishlisted games from EnhancedBarter." even if they regularly allow offers for any unowned game.

Most likely Implementation Idea: Users to have the ability to have the flexibility to have a bot receive preferences similar to the Offer Preferences section on the main user page. eg: Even if users normally are configured to be ok to receive offers involving games that are 60%+ in rating from users, they can specify that they only want to receive offers involving games that are 90%+ in rating from EnhancedBarter.

Extreme Implementation Idea: Using the browse filtering [ https://barter.vg/browse/ ] as the basis for what games users are willing to receive from EnhancedBarter. eg: Beyond the most likely implementation users can state they only want to receive offers involving games that have only been bundled X or fewer times or games that have at least X reviews.

**Comment by Revadike** [comment]
I don't see why offer preferences should be different for offers coming from Enhanced Barter or native barter. Both type of offers are crafted by regular traders. The only difference being that for native offers you select specific games and for enhanced offers you select a range. 
That said, barter will also improve the offer preferences soon. Maybe you can ask him for the desired changes.
