### ISSUE TITLE
Add feedback to steam profile 

### ISSUE THREAD

**Issue by Phoder1** [Revadike/EnhancedBarter#20]
Sending the feedback message sent to steamtrade, also to the trader steam profile as a comment.

**Comment by Revadike** [comment]
Fun fact. This used to be a feature, but then I got a temporary community ban from it. Turns out if you're trading a lot and leaving a lot of +rep messages with a link to the trade, steam considers you a spambot.

**Comment by Phoder1** [comment]
Wow, did not know that, well great job then :)
