### ISSUE TITLE
Cancel offers automatically

### ISSUE THREAD

**Issue by kaioloureiro** [Revadike/EnhancedBarter#23]
Please add the option to auto cancel the remaining offers with a tradable that isn't available anymore after a successful trade (if the "Update Collections" button is enabled and this tradable was the only one in the offer) or to remove that tradable from all the offers with it in and resend that offer without that specified tradable.

This will help us to avoid problems when using the "Begin Automated Offer" button to send multiple offers and more people than expected accept the offers (ex: 5 people accept the offers and I only have 3 copies of that tradable to trade).

The "Cancel Offers" button is worthy when that tradable is the only one in the offer, but when there's more than one tradable on the offer and I don't have anymore copies of a specific tradable, I need to edit every single offer to remove it.

**Comment by bartervg** [comment]
https://github.com/bartervg/barter.vg/issues/9
