### ISSUE TITLE
Filter by curator copies in upcoming feature

### ISSUE THREAD

**Issue by The-Numbers** [Revadike/EnhancedBarter#28]
In the upcoming feature you can filter by platform, availability, and users and I asked about filtering by curator copies. You told me to add this to the issues list
![Screenshot_2](https://user-images.githubusercontent.com/82730269/140437497-3a8bcdd6-4ace-49d1-a40b-09d2f8dc74bc.png)
.

**Comment by Revadike** [comment]
Please tell me more about this filter in detail

**Comment by The-Numbers** [comment]
Under the platform option, be able to filter by curator connect copies. For instance, you typically trade curator games and I would like to be able to quickly filter by all curator or dev key games available.
![Screenshot_1](https://user-images.githubusercontent.com/82730269/140438196-637e7a56-484f-4393-8dca-269997f92bf4.png)

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/140439294-db5baf06-5d37-4756-8b57-67c7721593e9.png)
You mean this?

**Comment by The-Numbers** [comment]
I mean that works, but the majority of traders do not indicate a deadline. That only works for your goods, and I can just hit ctrl f already for that

**Comment by Revadike** [comment]
Ok, I'll fix this next release:

![image](https://user-images.githubusercontent.com/4411977/140440965-eb26f840-fd13-49e1-aca7-149566bb1e26.png)
