### ISSUE TITLE
100 limit and other tradable list

### ISSUE THREAD

**Issue by aruedas** [Revadike/EnhancedBarter#32]
Hi. Great Job on this script.
I use it for my trading needs. What I do is the following:
I find tradable games with similar prices according to GG, then I send the script running for my wishlist.
Problem:
I have to manually add the 100 games I want to trade. Also, I have to remove my full tradable list and add a similar prices trading list to receive decent trades. 

Suggestion:
Letting add full lists of tradable lists from barter lists, perhaps. All items in the tradable lists has to be similar value, so the settings could be valid. 
This way, I could add lists of 1 dollar games to trade for 1 dollar games to trade 2x1 off my wishlist. Then on a different run, I could a list of tradable games for 2 dollars that can be traded 1x1.

On the current version, your list of tradable has to manually be added, so you don't end up giving valuable items for a less price. That is too much work for each run.

**Comment by Revadike** [comment]
I do not understand. Also, I cannot use gg.deals data.
