### ISSUE TITLE
Tradable list options

### ISSUE THREAD

**Issue by aruedas** [Revadike/EnhancedBarter#33]
There should be options to select 100 games automatically by price. Price is the ultimate MAIN trading value.
So an option to select 100 0-1 dollar games to trade based on GG then you can select your options as usual. An option to select 100 1.1-2, 2.1-3, etc. Ranges based on prices should be the most important modification to this script.
Prices can be measured easily. 

Great job on an excellent script.

**Comment by Revadike** [comment]
> Price is the ultimate MAIN trading value.

Subjective.

> based on GG 

I cannot use gg.deals data for sorting/filtering. They can only be retrieved by user action. It's not my intention to scrape gg.deals and burden their resources.
