### ISSUE TITLE
Option to automatically show gg.deals price info

### ISSUE THREAD

**Issue by natelovesyou** [Revadike/EnhancedBarter#37]
Currently you have to click the "GG" button in order to load the price info. In an offer where there are dozens of games, this can be a bit of a pain.

An option to do this on page load/refresh would be great, however, but I don't see that Enhanced Barter has a GUI to toggle options.

I've looked at the Edit page via TamperMonkey, but I'm no programmer or scripter so it's far from clear on if there's a way to toggle this. If there is, it isn't easy for the layman.

Thank you so far for what Enhanced Barter does!

**Comment by Revadike** [comment]
It's possible, but it can lead to spamming gg.deals, which I want to avoid.

**Comment by natelovesyou** [comment]
Hmm, that's fair I suppose. Thanks.
