### ISSUE TITLE
error message running - Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by aruedas** [Revadike/EnhancedBarter#38]
Last time I ran out the script it stalls and I've got the following error message:
Unexpected token '<', "<!DOCTYPE "... is not valid JSON

![enhancedbartererror](https://user-images.githubusercontent.com/42197527/193400390-20b848e7-f8ff-4201-bdb0-1e356aae18cf.png)

**Comment by Revadike** [comment]
steam-tracker was down

**Comment by aruedas** [comment]
thanks
