### ISSUE TITLE
GG.deals Automatcher didn't respect matching choices

### ISSUE THREAD

**Issue by tobimori** [Revadike/EnhancedBarter#41]
When recently running the GG.deals auto matcher, the bot created the following trade:
https://barter.vg/u/4349/o/5059310/

While my preferences were obviously set to only allow wishlist games. The game was also not shown on the match page itself.
![image](https://user-images.githubusercontent.com/29142128/201158974-01e9a0ae-5df0-4f93-adf8-671f5bcd2af8.png)

I have no clue how you might be able to reproduce it, sorry.

**Comment by Revadike** [comment]
Also, nice name suggestion :)

**Comment by aruedas** [comment]
How do you use the GG.deals auto matcher ?
I want to test this feature, but haven't found it.

**Comment by Revadike** [comment]
> How do you use the GG.deals auto matcher ? I want to test this feature, but haven't found it.

https://barter.vg/u/my/t/m/

**Comment by aruedas** [comment]
Where are the gg prices? I don't see the gg.deals part.

**Comment by aruedas** [comment]
Can you please send screenshots on how to access it?

**Comment by aruedas** [comment]
I see now the option. I was blind

**Comment by aruedas** [comment]
https://barter.vg/u/7df3/o/5026607/
same bug here

**Comment by jpenalbae** [comment]
Has this option been removed? I cannot see the automatch option on the matchs page...

![trades](https://user-images.githubusercontent.com/8380459/218606522-5017f536-4aef-4194-a23e-d4df04475f53.png)
