### ISSUE TITLE
errror fetching barter.vg data

### ISSUE THREAD

**Issue by aruedas** [Revadike/EnhancedBarter#42]
![error fetching barter vg  data try](https://user-images.githubusercontent.com/42197527/201503080-8090770d-abcf-4d07-be0f-480cecb1db71.png)

**Comment by Revadike** [comment]
try again

**Comment by MarcovonSchmidt** [comment]
Hi, if you are talking about GG.Deals prices, which one you use for calculating the offer?

1. Official Stores
2. Keyshops

I usually look to the Keyshops prices to compare. Maybe you can build in an option to choose?

**Comment by Revadike** [comment]
make an issue
