### ISSUE TITLE
Error fetching barter.vg data

### ISSUE THREAD

**Issue by Madnesis** [Revadike/EnhancedBarter#44]
Hey,
First of all, I would like to say that I really enjoy your script, thanks for putting it up!
For the first time, I attempted using the "Send Automated Offers" feature but it's failing: 
![image](https://user-images.githubusercontent.com/44895793/202458796-64af778e-5aa7-4fa5-a93e-c659596c2e8f.png)
Any idea what could be the issue? Thanks!

**Comment by Revadike** [comment]
yes, the issue is barter.vg
just try again
