### ISSUE TITLE
Regional restrictions

### ISSUE THREAD

**Issue by otrazhenye** [Revadike/EnhancedBarter#46]
Will it be possible to make offers for people from certain regions? Or for gifts / keys with regional restrictions?
For example, I have several keys, they can only be used in China, the CIS countries or the Arab Emirates. I can send an offer to those who do not have them in the library, but I cannot remove from the offer people who cannot activate the key in their country.

**Comment by Revadike** [comment]
It already has region checks. If the user is from region X and the tradable is locked to region Y, it will not offer the tradable to this user.

**Comment by otrazhenye** [comment]
https://barter.vg/u/cfa/o/5144577/
Am I doing something wrong? this offer is sent automatically, the region tag is on. But he's clearly not from China.

**Comment by Revadike** [comment]
The problem is that barter does not have a designated region that includes china (except ROW):
![image](https://user-images.githubusercontent.com/4411977/209847014-1693a56c-12ec-4f62-9a72-0bafe50d8939.png)

Barter's system is a weird mess, since their region lock tags include both countries and "regions". It's difficult to handle it well.

**Comment by Revadike** [comment]
On top of that, their country selector (which is a separate thing of their region selection for whatever reason) does not even include china. 

![image](https://user-images.githubusercontent.com/4411977/209847480-5eb77ffc-708e-41be-8338-cdfa8967ecd6.png)

**Comment by otrazhenye** [comment]
![Скриншот 2022-12-28 20 13 55](https://user-images.githubusercontent.com/5456765/209848599-3bf2abb7-c304-44d1-94c2-2b1192daf61c.png)

it seems to me that the list of countries depends on the Region I'm in, but I have all available

**Comment by arseny92** [comment]
> Will it be possible to make offers for people from certain regions? Or for gifts / keys with regional restrictions?
> For example, I have several keys, they can only be used in China, the CIS countries or the Arab Emirates. I can send an offer to those who do not have them in the library, but I cannot remove from the offer people who cannot activate the key in their country.

It is already sort of possible, but seldom used due to lack of manual labor resources. Blocker on [upstream](https://github.com/bartervg/barter.vg/issues/208).

**Comment by Revadike** [comment]
@otrazhenye

would you like to test a potential fix?

**Comment by otrazhenye** [comment]
of course

**Comment by Revadike** [comment]
> of course

Revadike#3529 on discord
