### ISSUE TITLE
Change offers options

### ISSUE THREAD

**Issue by Revadike** [Revadike/EnhancedBarter#5]
Instead of only altering offers to change expiry dates, also add other options:
 - remove/add games from either side
 - change ratio
 - change expiry time (already exists)

**Comment by Ot4islen** [comment]
Hi, I would like to see the ability to exclude the addition of games to the exchange, which are currently free in Steam, as well as banned. Is this being considered?

**Comment by Ot4islen** [comment]
It would be cool if this script could update sent exchanges, that is remove from them the games that I already received during the previous exchange

**Comment by Revadike** [comment]
> It would be cool if this script could update sent exchanges, that is remove from them the games that I already received during the previous exchange

Yup, I know. I've campaigning for barter to add this feature natively. I hesitant to add stuff to this script, while it can much better be added to the site instead.
