### ISSUE TITLE
 How do I disable auto rep on SteamTrades/Steam Profile?

### ISSUE THREAD

**Issue by velvellie** [Revadike/EnhancedBarter#57]
How do I disable it? It's a cool feature. I can see it being time-saving especially for traders that receive and complete a lot of trade offers. I only do trades every once in a while though so I don't need it. To be honest, I'd rather make my own review than make an automated, same-y review after every trade (for the time being at least).

**Comment by Revadike** [comment]
I'm fairly certain I added an option for it. I think somewhere before you hit the complete button. Anyways, it won't be relevant anymore in less than a month when barter is shutting down.

**Comment by velvellie** [comment]
> I'm fairly certain I added an option for it. I think somewhere before you hit the complete button. Anyways, it won't be relevant anymore in less than a month when barter is shutting down.

Oh I didn't catch that before I pressed the complete button. I'll look for it next time
